#!/usr/bin/ash

run_hook() {
    if [ -n "${cryptdevice}" ]; then
        IFS=: read cryptdev cryptname cryptoptions <<EOF
$cryptdevice
EOF
        kpartx -a "/dev/mapper/${cryptname}"
        if [ $? -ne 0 ]; then
            err "The command \"kpartx -a /dev/mapper/${cryptname}\" did not run successfully!"
            return 1
        fi
    fi
}

# vim: set ft=sh ts=4 sw=4 et:
