name: Release

on:
  create:
    tags:
      - "*"

jobs:
  release_automation:
    name: makepkg
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Hack makepkg
        run: |
          sed -i '/E_ROOT/d' /usr/bin/makepkg

      - name: Update database
        run: |
          pacman --noconfirm --noprogressbar -Sy

      - name: Build package
        run: |
          makepkg -sf --noconfirm

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            *.tar.zst
          name: ${{ github.event.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

